initial_tape = "0000011"
initial_state = "q0"
[q0]
0 = {write = "1", direction ="R", next_state = "q0"}
1 = {write = "0", direction = "R", next_state = "q1"}

[q1]
0 = {write = "1", direction = "R", next_state = "q2"}
1 = {write = "0", direction = "R", next_state = "halt"}

[halt]
